use_frameworks!



target 'iOS' do
  # platform :ios, '9.0'

  pod 'PoporFrameOc', :path => '../'
  
end

target 'macOS' do
  platform :osx, '10.6'
  
  pod 'PoporFrameOc', :path => '../'
  
end


target 'tvOS' do
  # platform :osx, '10.6'
  
  pod 'PoporFrameOc', :path => '../'
  
end
